const $=s=>document.querySelector(s);let token=localStorage.getItem("sk_token"),img=null,style="pencil",loginMode=true;
function openModal(view="login"){ $("#modal").classList.add("show"); $("#loginView").classList.toggle("hidden",view!=="login"); $("#payView").classList.toggle("hidden",view!=="pay");}
$("#authBtn").onclick=()=>openModal("login");$("#premiumBtn").onclick=()=>token?openModal("pay"):openModal("login");$("#close").onclick=()=>$("#modal").classList.remove("show");
$("#switchAuth").onclick=()=>{loginMode=!loginMode;$("#authTitle").textContent=loginMode?"Login":"Create account";$("#submitAuth").textContent=loginMode?"Login":"Sign up";$("#switchAuth").textContent=loginMode?"Create an account":"I already have an account";$("#authError").textContent=""};
$("#submitAuth").onclick=async()=>{try{const r=await fetch(loginMode?"/api/auth/login":"/api/auth/signup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:$("#email").value,password:$("#password").value})});const d=await r.json();if(!r.ok)throw Error(d.error);token=d.token;localStorage.setItem("sk_token",token);$("#modal").classList.remove("show");refreshMe()}catch(e){$("#authError").textContent=e.message}};
async function refreshMe(){if(!token)return;const r=await fetch("/api/me",{headers:{Authorization:"Bearer "+token}});if(!r.ok){token=null;localStorage.removeItem("sk_token");return}const d=await r.json();$("#dashboard").classList.remove("hidden");$("#dashEmail").textContent=d.user.email;$("#dashPlan").textContent=d.user.plan==="premium"?"Premium":"Free";$("#authBtn").textContent="Dashboard"}
$("#logout").onclick=()=>{token=null;localStorage.removeItem("sk_token");location.reload()};
document.querySelectorAll(".style").forEach(b=>b.onclick=()=>{document.querySelectorAll(".style").forEach(x=>x.classList.remove("active"));b.classList.add("active");style=b.dataset.style;if(img)makeArt()});
$("#file").onchange=e=>{const f=e.target.files[0];if(!f)return;const u=URL.createObjectURL(f);img=new Image();img.onload=()=>{const s=Math.min(1,1400/Math.max(img.width,img.height)),w=img.width*s,h=img.height*s;$("#original").width=$("#result").width=w;$("#original").height=$("#result").height=h;$("#original").getContext("2d").drawImage(img,0,0,w,h);$("#generate").disabled=false;$("#status").textContent="Photo loaded — choose a style and generate.";URL.revokeObjectURL(u)};img.src=u};
$("#generate").onclick=makeArt;
function makeArt(){if(!img)return;const a=$("#original"),b=$("#result"),w=a.width,h=a.height,src=a.getContext("2d").getImageData(0,0,w,h).data,g=new Float32Array(w*h),out=new Uint8ClampedArray(w*h*4);for(let i=0,p=0;i<g.length;i++,p+=4)g[i]=.299*src[p]+.587*src[p+1]+.114*src[p+2];const mult=style==="ink"?2.5:style==="charcoal"?1.4:style==="soft"?.8:1.9;for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){let i=y*w+x,gx=-g[i-w-1]-2*g[i-1]-g[i+w-1]+g[i-w+1]+2*g[i+1]+g[i+w+1],gy=-g[i-w-1]-2*g[i-w]-g[i-w+1]+g[i+w-1]+2*g[i+w]+g[i+w+1],v=255-Math.min(255,Math.hypot(gx,gy)*mult)*(style==="charcoal"?2.1:1.5);if(style==="soft")v=235-Math.min(255,Math.hypot(gx,gy)*mult)*.7;let p=i*4;v=Math.max(0,Math.min(255,v));out[p]=out[p+1]=out[p+2]=v;out[p+3]=255}b.getContext("2d").putImageData(new ImageData(out,w,h),0,0);$("#download").disabled=false;$("#status").textContent="Preview ready ✓"}
$("#download").onclick=async()=>{if(!token){openModal("login");return}const me=await fetch("/api/me",{headers:{Authorization:"Bearer "+token}}).then(r=>r.json());if(me.user?.plan!=="premium"){openModal("pay");return}const a=document.createElement("a");a.download="sketchify-hd.png";a.href=$("#result").toDataURL("image/png");a.click()};
$("#checkout").onclick=async()=>{try{const r=await fetch("/api/payment/create-order",{method:"POST",headers:{Authorization:"Bearer "+token}}),d=await r.json();if(!r.ok)throw Error(d.error);const rz=new Razorpay({key:d.keyId,amount:d.amount,currency:d.currency,name:"Sketchify AI",description:"Premium monthly plan",order_id:d.orderId,prefill:{email:$("#email").value},handler:async response=>{const v=await fetch("/api/payment/verify",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify(response)});const x=await v.json();if(x.ok){$("#modal").classList.remove("show");refreshMe();alert("Premium activated!")}else alert(x.error)}});rz.open()}catch(e){alert(e.message)}};
refreshMe();